spring:
  application:
    name: fintrack-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5671
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

fintrack:
  api-key:
    secret: ${API_KEY_SECRET}
  rabbitmq:
    exchange: fintrack.transactions
    routing-key-transaction: transaction.TRANSACTION
  ingestion:
    batch-size-limit: 1000
    dedup-ttl-hours: 24
    adapters:
      enabled:
        - CREDIT
        - DEBIT
        - LOANS
        - INVESTMENTS